# Site settings
## Change the values as needed.
title: Kattappa
email: brijeshb42@gmail.com
description: "A block based rich text editor made using React"
keywords: "react, editor, block, trevor"
url: "http://bitwiser.in/kattappa" # the base hostname & protocol for your site
baseurl: "http://bitwiser.in/kattappa" # the subpath of your site, e.g. /blog/
#url: ""
#baseurl: ""
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
links:
  twitter: brijeshb42
  github: brijeshb42/kattappa/
exclude:
  - bower_components
  - README.md
  - bower.json
  - src
  - package.json
full_name: Brijesh

##set this to enable disqus commenting
#disqus: forumname

##set this to enable google analytics
ga_id: UA-47902363-1
ga_domain: bitwiser.in
